version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "samgithubactions"
s3_prefix = "sam-app"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

